### ISSUE TITLE
Can't convert 'bytes' object to str implicitly

### ISSUE THREAD

**Issue by zhoushaobo1015** [suxianbaozi/pywebsocketserver#2]
你好，我才开始学习python使用python3 跑你的脚本时候发现出现这个问题
self.buffer += self.conn.recv(1024) 这行代码出现的错误TypeError: Can't convert 'bytes' object to str implicitly 不知道如何处理

**Comment by suxianbaozi** [comment]
我这只兼容到2.7  3.0还没开始兼容呐，
不过初学者建议先搞2.7
