### ISSUE TITLE
测试，发现 部分浏览器 不支持 

### ISSUE THREAD

**Issue by xty19** [suxianbaozi/pywebsocketserver#3]
客户端浏览器使用情况如下：
不支持的浏览器：
1. ie 2. 360se  3.Safari（iphone） 4.Safari （macos） 5.Uc （iphone）

支持的浏览器：
1.火狐 2.chrome

**Comment by suxianbaozi** [comment]
嗯  safari的 握手协议不太一样，这个你是否可以帮我改一下？  
IE 还没空研究...估计也是握手协议有问题

**Comment by xty19** [comment]
@suxianbaozi 
我高兴帮你改，但是你的源码部分，thread.py 没读懂，暂时不知道怎么修改，或者说一下修改的思路，谢谢

**Comment by suxianbaozi** [comment]
@xty19 thread.py主要是用来处理每个socket链接的websockt的具体通信协议的，你得去研究一下websocket的握手协议才可以进行修改，我这个周末抽空来改一下吧，这东西是我五年前写的，现在去看，很多不满意的地方

**Comment by xty19** [comment]
@suxianbaozi 好的，麻烦了啊，学了不少东西。

**Comment by xty19** [comment]
@suxianbaozi 修改了吗？

**Comment by suxianbaozi** [comment]
不好意思哈，最近一直忙，我测试了一下 ie 10 以上是支持的，因为ie9根本就不支持websocket 所以就没办法啦，我正在调试safari相关的 东西，应该这周肯定能出来

**Comment by suxianbaozi** [comment]
已经解决了，纯粹是一个换行引发的血案

python的  base64.encodestring 会给自动加上一个\n

**Comment by xty19** [comment]
@suxianbaozi 
👍 
好的，我有时间测试下，时隔几年了，但是小错误什么时候都很致命啊

**Comment by xty19** [comment]
@suxianbaozi 
我测试了，你修改完的，浏览器都不可用了，而且局域网也没法访问。

原版的之前可以局域网访问的。

**Comment by suxianbaozi** [comment]
我刚刚又测试了一下，发现没啥问题呀

**Comment by xty19** [comment]
假如运行服务器的电脑ip是192.168.1.100，
路径是 ../pywebsocketserver/demo.htm
端口是8080
其他局域网主机怎么访问？

**Comment by suxianbaozi** [comment]
demo.html里的ip改成 100
其他局域网能访问到demo.html就行了

**Comment by xty19** [comment]
@suxianbaozi 
好的，我一会测试下

**Comment by xty19** [comment]
我测试了。
1.直接打开本地文件demo.htm 没有问题
2.我把demo.htm放倒 /var/www/html/ 下面，用的 nginx （tomcat 也是如此）服务器,局域网 用户访问时，除了 Chrome，火狐，还有苹果手机Safari （Mac Safari 不可用）以外，其他浏览器还是不可以，具体原因不详，我一会再试试用其他的服务器 映射 demo 文件。

**Comment by xty19** [comment]
@suxianbaozi 
我回家用家里的笔记本，手机，平板测试了，
浏览器包括：
ie11，360se(ie11 内核) ，火狐，chrome，Mac Safari，iphone Safari，安卓 自带浏览器，进行了测试。

结果如下，仅有 ie( 8,9 )以及使用其内核 的 360se (注：!!!360se 却可以 直接打开demo.htm 访问文件进行通信) 无法通讯，其他都成功通讯！
再次谢谢博主 @suxianbaozi

**Comment by suxianbaozi** [comment]
ie 8,9 不支持websocket ,这个没办法。。。。如果你是在要实现这俩浏览器，可以去看看我另外一个项目

https://github.com/suxianbaozi/websocket4ie

**Comment by suxianbaozi** [comment]
另外要多谢你的测试啦

**Comment by xty19** [comment]
@suxianbaozi 哈哈，我这就看看去
